 POST http://localhost:8080/api/v1/appointment 
Content-Type: application/json

{
    "date": "2023-09-30",
    "hour": "17:00",
    "email": "franmelerogallardo@gmail.com",
    "name": "Franky",
    "duration": "15",
    "token": "66666632",
    "serviceid": 2,
}

